# Generated by Django 3.2 on 2021-05-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210506_1953'),
    ]

    operations = [


        migrations.AlterField(
            model_name='eachclass',
            name='Earnestpeopl',
            field=models.BigIntegerField(),
        ),
    ]
