# Generated by Django 3.2 on 2021-05-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210506_2006'),
    ]

    operations = [

        migrations.AlterField(
            model_name='eachclass',
            name='Focusvalue',
            field=models.BigIntegerField(),
        ),
    ]
